- name: nginx install and run
  hosts: web
  become: yes # changes to sudo access
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present # present == install remove == absent

